CREATE TABLE Books (
    BookId INT IDENTITY(1,1) PRIMARY KEY , 
    BookTitle NVARCHAR(250) NOT NULL, 
    price INT NOT NULL,
    publisher NVARCHAR(255),
    publishedDate nvarchar(20), 
    [description] NVARCHAR(2000), 
    pageNum INT,
    averageRating INT, 
    ratingsCount INT, 
    smallThumbnailUrl NVARCHAR(255),
    thumbnailUrl NVARCHAR(255),
    lang NVARCHAR(20),
    previewLink NVARCHAR(255),
    infoLink NVARCHAR(255), 
    canonicalVolumeLink nVARCHAR(255), 
    isEbook bit not null, 
    embeddable bit,
    epubIsAvailable bit,
    epubDownloadLink NVARCHAR(255),
    pdfIsAvailable bit, 
    pdfDownloadLink NVARCHAR(255),
    webReaderLink NVARCHAR(255),
	textReading bit, 
	photoReading bit,
    googleBooksId NVARCHAR(250),
    etag NVARCHAR(250),
    selfLink NVARCHAR(255) 
);